### ISSUE TITLE
Is it possible to add it as a package dependencies for new IOS project?

### ISSUE THREAD

**Issue by asnov** [apple/swift-async-dns-resolver#17]
Hello!
Thank you for your great package.
I have one issue. When I add it as a package dependencies to the IOS project without Package.swift, it gives me a lot of
`Concurrency is only available in iOS 13.0.0 or newer` errors in the `swift-async-dns-resolver/Sources/AsyncDNSResolver/AsyncDNSResolver.swift` file.

I'm adding it this way:
Xcode -> File -> Add Package Dependencies... -> swift-async-dns-resolver -> Add Package

Here is the demo project: https://github.com/asnov/AsyncDNSResolverDemoIOS

Thank you!

**Comment by mkbrwr** [comment]
Hello, in Package.swift under platforms only .macOS("13.0") is listed, you can make a local copy of a package and add .iOS("13.0") there and it should build. But I'm also curious why support for iOS is not listed

**Comment by asnov** [comment]
@yim-lee I  tried what @mkbrwr suggested. I needed to clone with submodules: `git clone https://github.com/apple/swift-async-dns-resolver.git --recurse-submodules`. And it works fine. So you could add iOS to the platforms.
Thank you!

**Comment by yim-lee** [comment]
Thanks @asnov. Opened: https://github.com/apple/swift-async-dns-resolver/pull/19

**Comment by yim-lee** [comment]
Patch: https://github.com/apple/swift-async-dns-resolver/releases/tag/0.1.4
