### ISSUE TITLE
Error: other [-65563]: under MacOS

### ISSUE THREAD

**Issue by asnov** [apple/swift-async-dns-resolver#18]
Hello!
I need to use DNS resolution inside multi-platform app so I need this package to run under IOS and MacOS.
When I try to run it under MacOS `resolver.queryA(name: "apple.com")` gives me an `other [-65563]:` error.
Any idea how can I solve it?

Here is a demo project: https://github.com/asnov/AsyncDNSResolverDemoMacOS
Here is what I can see in the console:
```
Error: other [-65563]: 
AsyncDNSResolverDemoMacOS/Resolver.swift:34: Fatal error: DNS query throwed!
```
What am I doing wrong?
Thank you!

**Comment by mkbrwr** [comment]
This might help https://forums.developer.apple.com/forums/thread/67792

**Comment by asnov** [comment]
It helped as well. @mkbrwr  Thank you very much!

**Comment by yim-lee** [comment]
🥳
