### ISSUE TITLE
Package does not build for iOS. Error "Concurrency is only available in iOS 13.0.0 or newer"

### ISSUE THREAD

**Issue by mkbrwr** [apple/swift-async-dns-resolver#25]
When building iOS application with this packet I get error in file AsyncDNSResolver.swift "Concurrency is only available in iOS 13.0.0 or newer"
The issues seems to be that `public protocol DNSResolver` is missing `@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)`
This started to happen after commit 62fbedd992abf97e83549dde7c7cf9ab7b74c8d8

**Comment by yim-lee** [comment]
@mkbrwr Thanks for reporting. Would you be able to test if https://github.com/apple/swift-async-dns-resolver/pull/26 fixes the issue for you?

**Comment by mkbrwr** [comment]
@yim-lee I've tested #26 and it fixes the issue. Thank you! Also I have a question, is it possible to add some kind of a test that will verify if package builds for iOS ?

**Comment by yim-lee** [comment]
Thanks @mkbrwr. Sorry for the trouble. This release includes the fix: https://github.com/apple/swift-async-dns-resolver/releases/tag/0.3.0

> is it possible to add some kind of a test that will verify if package builds for iOS

This is something we want but unfortunately don't have yet.
