### ISSUE TITLE
Possible memory leaks in Ares.query and AQueryReplyParser / AAAAQueryReplyParser

### ISSUE THREAD

**Issue by dieb** [apple/swift-async-dns-resolver#29]
Hi there,

I'm using the Xcode Leaks to inspect my app and leaks are showing up when using the lib (v0.3.0). Same leaks were showing up before I upgraded (v0.1.3).

I noticed two potential sources of leaks:
1) Continuation leaking in `Ares.query`: https://github.com/apple/swift-async-dns-resolver/blob/main/Sources/AsyncDNSResolver/c-ares/DNSResolver_c-ares.swift#L148
2) Hostent is leaking in [AQueryReplyParser and AAAAQueryReplyParser](https://github.com/apple/swift-async-dns-resolver/blob/main/Sources/AsyncDNSResolver/c-ares/DNSResolver_c-ares.swift#L309) and maybe others but I'm only doing A/AAAA

Possible explanation for 1): see PR #31 

Possible explanation for 2) : ares_parse_a_reply will create hostent and fill it out [here](https://github.com/c-ares/c-ares/blob/cares-1_19_1/src/lib/ares_parse_a_reply.c#L67) which then allocates stuff in [addrinfo2hostent](https://github.com/c-ares/c-ares/blob/cares-1_19_1/src/lib/ares__addrinfo2hostent.c#L58). It looks like it has the expectation the caller will call `freehostent(hostent)`. Looks like we can pass host=null and and it won't allocate for *host (this worked and leaks are gone PR - #30 ). We aren't using hostent anyways.

Screenshots below.

![Screenshot 2024-02-20 at 9 47 03 PM](https://github.com/apple/swift-async-dns-resolver/assets/75843/ed102ed2-aaf5-4bdd-b859-03134cd6d593)

![Screenshot 2024-02-20 at 9 46 54 PM](https://github.com/apple/swift-async-dns-resolver/assets/75843/46178ad8-d03c-443b-be3d-e61d7a623d7a)

![Screenshot 2024-02-20 at 9 46 44 PM](https://github.com/apple/swift-async-dns-resolver/assets/75843/35fa166b-e84f-4e9c-9e7b-6d0421d5215f)

How my app uses the lib (note: I don't reuse AsyncDNSResolver, it gets collected): 

```swift
var options = CAresDNSResolver.Options.default
options.timeoutMillis = 200
options.servers = Constants.DNSServers
options.rotate = true
resolver = try AsyncDNSResolver(options: options)
```

Querying
```swift
let aRecords = try? await resolver.queryA(name: hostname)
let aaaaRecords = try? await resolver.queryAAAA(name: hostname)

let a = aRecords?.map { aRecord in
    Record(address: aRecord.address.description, ttl: aRecord.ttl.map { Int($0) } ?? DNSResolver.defaultTTL)
}

let aaaa = aaaaRecords?.map { aaaaRecord in
    Record(address: aaaaRecord.address.description, ttl: aaaaRecord.ttl.map { Int($0) } ?? DNSResolver.defaultTTL)
}
```

**Comment by yim-lee** [comment]
Patch release that includes the fixes: https://github.com/apple/swift-async-dns-resolver/releases/tag/0.3.1
